[project]
name = "f1-race-replay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arcade>=3.3.3",
    "fastf1>=3.7.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "typer>=0.20.0",
]
